# Generated by Django 5.1.7 on 2025-04-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='DefaultUser', max_length=255),
            preserve_default=False,
        ),
    ]
